[package]
name = "bevy-bootstrapper" # BOOTSTRAPPER: Change this for the name of your package
version = "0.1.0"          # BOOTSTRAPPER: Change this for the version of your package
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# --------
# OPTMIZATION: Optimize the dev profiles to run smoothly.

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
# --------

# --------
# OPTMIZATION: Optimize the release profiles to run smoothly, at the cost of compile time.

# Enable more optimization in the release profile at the cost of compile time.
[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

# Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
[profile.wasm-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"
# --------

[dependencies]
# IMPORTANT: Dynamic linking is enabled and must be disabled when building for release
bevy = { version = "0.18.1", features = ["dynamic_linking"] }
# OPTIMIZATION: Improves runtime performances by stripping trace logging
log = { version = "*", features = [
  "max_level_debug",
  "release_max_level_warn",
] }
